In [5]:
import pandas as pd

fund_master = pd.read_csv(r"C:\Users\madhu\mutual_fund_analytics\data\raw\01_fund_master.csv")
nav_history = pd.read_csv(r"C:\Users\madhu\mutual_fund_analytics\data\raw\02_nav_history.csv")
aum_by_fund_house = pd.read_csv(r"C:\Users\madhu\mutual_fund_analytics\data\raw\03_aum_by_fund_house.csv")
monthly_sip_inflows = pd.read_csv(r"C:\Users\madhu\mutual_fund_analytics\data\raw\04_monthly_sip_inflows.csv")
category_inflows = pd.read_csv(r"C:\Users\madhu\mutual_fund_analytics\data\raw\05_category_inflows.csv")
industry_folio_count = pd.read_csv(r"C:\Users\madhu\mutual_fund_analytics\data\raw\06_industry_folio_count.csv")
scheme_performance = pd.read_csv(r"C:\Users\madhu\mutual_fund_analytics\data\raw\07_scheme_performance.csv")
investor_transactions = pd.read_csv(r"C:\Users\madhu\mutual_fund_analytics\data\raw\08_investor_transactions.csv")
portfolio_holdings = pd.read_csv(r"C:\Users\madhu\mutual_fund_analytics\data\raw\09_portfolio_holdings.csv")
benchmark_indices = pd.read_csv(r"C:\Users\madhu\mutual_fund_analytics\data\raw\10_benchmark_indices.csv")

datasets = {
    "01_fund_master": fund_master,
    "02_nav_history": nav_history,
    "03_aum_by_fund_house": aum_by_fund_house,
    "04_monthly_sip_inflows": monthly_sip_inflows,
    "05_category_inflows": category_inflows,
    "06_industry_folio_count": industry_folio_count,
    "07_scheme_performance": scheme_performance,
    "08_investor_transactions": investor_transactions,
    "09_portfolio_holdings": portfolio_holdings,
    "10_benchmark_indices": benchmark_indices
}

for name, df in datasets.items():

    print("\n" + "=" * 80)
    print("DATASET:", name)

    print("\nSHAPE:")
    print(df.shape)

    print("\nDATA TYPES:")
    print(df.dtypes)

    print("\nFIRST 5 ROWS:")
    print(df.head())

    print("\nMISSING VALUES:")
    print(df.isnull().sum())

    print("\nDUPLICATE ROWS:")
    print(df.duplicated().sum())

================================================================================
DATASET: 01_fund_master

SHAPE:
(40, 15)

DATA TYPES:
amfi_code               int64
fund_house             object
scheme_name            object
category               object
sub_category           object
plan                   object
launch_date            object
benchmark              object
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager           object
risk_category          object
sebi_category_code     object
dtype: object

FIRST 5 ROWS:
   amfi_code       fund_house                                   scheme_name  \
0     119551  SBI Mutual Fund     SBI Bluechip Fund - Regular Plan - Growth
1     119552  SBI Mutual Fund      SBI Bluechip Fund - Direct Plan - Growth
2     119598  SBI Mutual Fund    SBI Small Cap Fund - Regular Plan - Growth
3     119599  SBI Mutual Fund     SBI Small Cap Fund - Direct Plan - Growth
4     119120  SBI Mutual Fund  SBI Magnum Gilt Fund - Regular Plan - Growth

  category sub_category     plan launch_date                  benchmark  \
0   Equity    Large Cap  Regular  2006-02-14              NIFTY 100 TRI
1   Equity    Large Cap   Direct  2013-01-01              NIFTY 100 TRI
2   Equity    Small Cap  Regular  2009-09-09       BSE 250 SmallCap TRI
3   Equity    Small Cap   Direct  2013-01-01       BSE 250 SmallCap TRI
4     Debt         Gilt  Regular  2000-12-30  CRISIL Dynamic Gilt Index

   expense_ratio_pct  exit_load_pct  min_sip_amount  min_lumpsum_amount  \
0               1.54            1.0             500                1000
1               0.66            1.0             500                1000
2               1.43            1.0             500                1000
3               0.72            1.0             500                1000
4               0.77            0.0             500                1000

    fund_manager risk_category sebi_category_code
0  Sohini Andani      Moderate               EC01
1  Sohini Andani      Moderate               EC01
2  R. Srinivasan     Very High               EC03
3  R. Srinivasan     Very High               EC03
4   Dinesh Ahuja           Low               DC02

MISSING VALUES:
amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

DUPLICATE ROWS:
0

================================================================================
DATASET: 02_nav_history

SHAPE:
(46000, 3)

DATA TYPES:
amfi_code      int64
date          object
nav          float64
dtype: object

FIRST 5 ROWS:
   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

MISSING VALUES:
amfi_code    0
date         0
nav          0
dtype: int64

DUPLICATE ROWS:
0

================================================================================
DATASET: 03_aum_by_fund_house

SHAPE:
(90, 5)

DATA TYPES:
date               object
fund_house         object
aum_lakh_crore    float64
aum_crore           int64
num_schemes         int64
dtype: object

FIRST 5 ROWS:
         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

MISSING VALUES:
date              0
fund_house        0
aum_lakh_crore    0
aum_crore         0
num_schemes       0
dtype: int64

DUPLICATE ROWS:
0

================================================================================
DATASET: 04_monthly_sip_inflows

SHAPE:
(48, 6)

DATA TYPES:
month                         object
sip_inflow_crore               int64
active_sip_accounts_crore    float64
new_sip_accounts_lakh        float64
sip_aum_lakh_crore           float64
yoy_growth_pct               float64
dtype: object

FIRST 5 ROWS:
     month  sip_inflow_crore  active_sip_accounts_crore  \
0  2022-01             11517                       4.91
1  2022-02             11438                       4.93
2  2022-03             12328                       5.09
3  2022-04             11863                       5.48
4  2022-05             12286                       5.55

   new_sip_accounts_lakh  sip_aum_lakh_crore  yoy_growth_pct
0                   9.10                4.80             NaN
1                   8.20                4.85             NaN
2                  10.50                5.01             NaN
3                   9.52                5.12             NaN
4                   8.10                5.15             NaN

MISSING VALUES:
month                         0
sip_inflow_crore              0
active_sip_accounts_crore     0
new_sip_accounts_lakh         0
sip_aum_lakh_crore            0
yoy_growth_pct               12
dtype: int64

DUPLICATE ROWS:
0

================================================================================
DATASET: 05_category_inflows

SHAPE:
(144, 3)

DATA TYPES:
month                object
category             object
net_inflow_crore    float64
dtype: object

FIRST 5 ROWS:
     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0

MISSING VALUES:
month               0
category            0
net_inflow_crore    0
dtype: int64

DUPLICATE ROWS:
0

================================================================================
DATASET: 06_industry_folio_count

SHAPE:
(21, 6)

DATA TYPES:
month                   object
total_folios_crore     float64
equity_folios_crore    float64
debt_folios_crore      float64
hybrid_folios_crore    float64
others_folios_crore    float64
dtype: object

FIRST 5 ROWS:
     month  total_folios_crore  equity_folios_crore  debt_folios_crore  \
0  2022-01               13.26                 9.28               1.86
1  2022-04               13.91                 9.74               1.95
2  2022-07               13.85                 9.69               1.94
3  2022-10               14.12                 9.88               1.98
4  2023-01               14.81                10.37               2.07

   hybrid_folios_crore  others_folios_crore
0                 0.80                 1.33
1                 0.83                 1.39
2                 0.83                 1.38
3                 0.85                 1.41
4                 0.89                 1.48

MISSING VALUES:
month                  0
total_folios_crore     0
equity_folios_crore    0
debt_folios_crore      0
hybrid_folios_crore    0
others_folios_crore    0
dtype: int64

DUPLICATE ROWS:
0

================================================================================
DATASET: 07_scheme_performance

SHAPE:
(40, 19)

DATA TYPES:
amfi_code               int64
scheme_name            object
fund_house             object
category               object
plan                   object
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade             object
dtype: object

FIRST 5 ROWS:
   amfi_code                                   scheme_name       fund_house  \
0     119551     SBI Bluechip Fund - Regular Plan - Growth  SBI Mutual Fund
1     119552      SBI Bluechip Fund - Direct Plan - Growth  SBI Mutual Fund
2     119598    SBI Small Cap Fund - Regular Plan - Growth  SBI Mutual Fund
3     119599     SBI Small Cap Fund - Direct Plan - Growth  SBI Mutual Fund
4     119120  SBI Magnum Gilt Fund - Regular Plan - Growth  SBI Mutual Fund

    category     plan  return_1yr_pct  return_3yr_pct  return_5yr_pct  \
0  Large Cap  Regular           12.42           12.36           14.45
1  Large Cap   Direct           15.25           11.30           14.23
2  Small Cap  Regular           24.56           23.39           20.67
3  Small Cap   Direct           20.59           23.14           21.82
4       Gilt  Regular            5.34            6.07            5.43

   benchmark_3yr_pct  alpha  beta  sharpe_ratio  sortino_ratio  \
0              11.49   0.87  0.89          0.88           1.29
1               9.52   1.78  0.87          0.81           1.29
2              22.16   1.23  0.89          0.94           1.35
3              22.01   1.13  1.04          0.93           1.67
4               4.47   1.60  0.22          1.52           2.11

   std_dev_ann_pct  max_drawdown_pct  aum_crore  expense_ratio_pct  \
0             14.0            -21.70      14288               1.54
1             14.0            -24.43       1231               0.66
2             25.0            -13.35      19259               1.43
3             25.0            -24.78      36061               0.72
4              4.0             -2.30      24101               0.77

   morningstar_rating risk_grade
0                   4   Moderate
1                   3   Moderate
2                   5  Very High
3                   4  Very High
4                   5        Low

MISSING VALUES:
amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

DUPLICATE ROWS:
0

================================================================================
DATASET: 08_investor_transactions

SHAPE:
(32778, 13)

DATA TYPES:
investor_id            object
transaction_date       object
amfi_code               int64
transaction_type       object
amount_inr              int64
state                  object
city                   object
city_tier              object
age_group              object
gender                 object
annual_income_lakh    float64
payment_mode           object
kyc_status             object
dtype: object

FIRST 5 ROWS:
  investor_id transaction_date  amfi_code transaction_type  amount_inr  \
0   INV003054       2024-01-01     119092              SIP        1834
1   INV002952       2024-01-01     148567       Redemption      392882
2   INV003420       2024-01-01     118636              SIP         912
3   INV003436       2024-01-01     118634              SIP        1102
4   INV004691       2024-01-01     119094          Lumpsum        8682

         state       city city_tier age_group  gender  annual_income_lakh  \
0    Telangana  Hyderabad       T30       56+  Female                77.1
1       Punjab   Amritsar       B30     18-25    Male                 7.1
2      Haryana  Faridabad       B30     36-45    Male                47.2
3  Maharashtra     Mumbai       T30     36-45  Female                54.4
4        Delhi      Noida       T30     26-35    Male                14.5

  payment_mode kyc_status
0          UPI   Verified
1       Cheque   Verified
2      Mandate   Verified
3       Cheque    Pending
4  Net Banking    Pending

MISSING VALUES:
investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

DUPLICATE ROWS:
0

================================================================================
DATASET: 09_portfolio_holdings

SHAPE:
(322, 8)

DATA TYPES:
amfi_code              int64
stock_symbol          object
stock_name            object
sector                object
weight_pct           float64
market_value_cr      float64
current_price_inr    float64
portfolio_date        object
dtype: object

FIRST 5 ROWS:
   amfi_code stock_symbol                stock_name       sector  weight_pct  \
0     119551    POWERGRID    Power Grid Corporation    Utilities       13.85
1     119551     HDFCBANK             HDFC Bank Ltd      Banking       11.19
2     119551       GRASIM     Grasim Industries Ltd  Diversified        9.90
3     119551      DRREDDY  Dr. Reddy's Laboratories       Pharma        4.76
4     119551   ASIANPAINT          Asian Paints Ltd       Paints       10.25

   market_value_cr  current_price_inr portfolio_date
0           737.09            6011.08     2025-12-31
1            88.97            1074.65     2025-12-31
2           208.45            5964.59     2025-12-31
3           161.32            3748.82     2025-12-31
4           725.90            1321.45     2025-12-31

MISSING VALUES:
amfi_code            0
stock_symbol         0
stock_name           0
sector               0
weight_pct           0
market_value_cr      0
current_price_inr    0
portfolio_date       0
dtype: int64

DUPLICATE ROWS:
0

================================================================================
DATASET: 10_benchmark_indices

SHAPE:
(8050, 3)

DATA TYPES:
date            object
index_name      object
close_value    float64
dtype: object

FIRST 5 ROWS:
         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

MISSING VALUES:
date           0
index_name     0
close_value    0
dtype: int64

DUPLICATE ROWS:
0

In [6]:
print("Fund Master Columns:")
print(fund_master.columns.tolist())

print("\n")

print("NAV History Columns:")
print(nav_history.columns.tolist())

Fund Master Columns:
['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category', 'plan', 'launch_date', 'benchmark', 'expense_ratio_pct', 'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager', 'risk_category', 'sebi_category_code']


NAV History Columns:
['amfi_code', 'date', 'nav']

In [7]:
# Explore Fund Master Dataset

print("Columns:")
print(fund_master.columns.tolist())

print("\nDataset Shape:")
print(fund_master.shape)

print("\nFirst 5 Rows:")
display(fund_master.head())

print("\nUnique Values Per Column:")
for col in fund_master.columns:
    print(f"\n{col}: {fund_master[col].nunique()} unique values")

Columns:
['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category', 'plan', 'launch_date', 'benchmark', 'expense_ratio_pct', 'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager', 'risk_category', 'sebi_category_code']

Dataset Shape:
(40, 15)

First 5 Rows:

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

Unique Values Per Column:

amfi_code: 40 unique values

fund_house: 10 unique values

scheme_name: 40 unique values

category: 2 unique values

sub_category: 12 unique values

plan: 2 unique values

launch_date: 34 unique values

benchmark: 10 unique values

expense_ratio_pct: 31 unique values

exit_load_pct: 3 unique values

min_sip_amount: 1 unique values

min_lumpsum_amount: 3 unique values

fund_manager: 29 unique values

risk_category: 5 unique values

sebi_category_code: 9 unique values

In [8]:
fund_master.columns.tolist()

['amfi_code',
 'fund_house',
 'scheme_name',
 'category',
 'sub_category',
 'plan',
 'launch_date',
 'benchmark',
 'expense_ratio_pct',
 'exit_load_pct',
 'min_sip_amount',
 'min_lumpsum_amount',
 'fund_manager',
 'risk_category',
 'sebi_category_code']

In [9]:
print("UNIQUE FUND HOUSES")
print(fund_master['fund_house'].unique())

print("\nTOTAL FUND HOUSES:")
print(fund_master['fund_house'].nunique())

print("\n" + "="*80)

print("CATEGORIES")
print(fund_master['category'].unique())

print("\nTOTAL CATEGORIES:")
print(fund_master['category'].nunique())

print("\n" + "="*80)

print("SUB CATEGORIES")
print(fund_master['sub_category'].unique())

print("\nTOTAL SUB CATEGORIES:")
print(fund_master['sub_category'].nunique())

print("\n" + "="*80)

print("RISK CATEGORIES")
print(fund_master['risk_category'].unique())

print("\nTOTAL RISK CATEGORIES:")
print(fund_master['risk_category'].nunique())

UNIQUE FUND HOUSES
['SBI Mutual Fund' 'HDFC Mutual Fund' 'ICICI Prudential MF'
 'Nippon India MF' 'Kotak Mahindra MF' 'Axis Mutual Fund'
 'Aditya Birla Sun Life MF' 'UTI Mutual Fund' 'Mirae Asset MF'
 'DSP Mutual Fund']

TOTAL FUND HOUSES:
10

================================================================================
CATEGORIES
['Equity' 'Debt']

TOTAL CATEGORIES:
2

================================================================================
SUB CATEGORIES
['Large Cap' 'Small Cap' 'Gilt' 'Mid Cap' 'Short Duration' 'Value'
 'Liquid' 'Index/ETF' 'Flexi Cap' 'Index' 'Large & Mid Cap' 'ELSS']

TOTAL SUB CATEGORIES:
12

================================================================================
RISK CATEGORIES
['Moderate' 'Very High' 'Low' 'High' 'Moderately High']

TOTAL RISK CATEGORIES:
5

In [10]:
nav_history.columns.tolist()

['amfi_code', 'date', 'nav']

In [11]:
fund_codes = set(fund_master['amfi_code'])
nav_codes = set(nav_history['amfi_code'])

missing_codes = fund_codes - nav_codes

print("Total AMFI Codes in Fund Master:", len(fund_codes))
print("Total AMFI Codes in NAV History:", len(nav_codes))

print("\nMissing Codes:")
print(missing_codes)

print("\nMissing Count:")
print(len(missing_codes))

Total AMFI Codes in Fund Master: 40
Total AMFI Codes in NAV History: 40

Missing Codes:
set()

Missing Count:
0

In [12]:
print("DATA QUALITY SUMMARY")
print("="*50)

print(f"Total Funds: {fund_master['amfi_code'].nunique()}")
print(f"Total Fund Houses: {fund_master['fund_house'].nunique()}")
print(f"Total Categories: {fund_master['category'].nunique()}")
print(f"Total Sub Categories: {fund_master['sub_category'].nunique()}")
print(f"Total Risk Categories: {fund_master['risk_category'].nunique()}")

print("\nMissing Values in Fund Master:")
print(fund_master.isnull().sum())

print("\nMissing Values in NAV History:")
print(nav_history.isnull().sum())

DATA QUALITY SUMMARY
==================================================
Total Funds: 40
Total Fund Houses: 10
Total Categories: 2
Total Sub Categories: 12
Total Risk Categories: 5

Missing Values in Fund Master:
amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

Missing Values in NAV History:
amfi_code    0
date         0
nav          0
dtype: int64

In [13]:
import requests
import pandas as pd

url = "https://api.mfapi.in/mf/125497"

response = requests.get(url)

data = response.json()

print("Scheme Name:")
print(data["meta"]["scheme_name"])

nav_df = pd.DataFrame(data["data"])

nav_df.head()

Scheme Name:
SBI Small Cap Fund - Direct Plan - Growth

         date        nav
0  01-06-2026  192.31950
1  31-05-2026  193.68360
2  29-05-2026  193.68480
3  27-05-2026  195.05010
4  26-05-2026  194.22580

In [14]:
nav_df.to_csv(
    r"C:\Users\madhu\mutual_fund_analytics\data\raw\HDFC_Top100_NAV.csv",
    index=False
)

print("File Saved Successfully")

File Saved Successfully

In [19]:
import requests
import pandas as pd

schemes = {
    "SBI_Bluechip": 119551,
    "ICICI_Bluechip": 120503,
    "Nippon_LargeCap": 118632,
    "Axis_Bluechip": 119092,
    "Kotak_Bluechip": 120841
}

for name, code in schemes.items():

    print(f"\nChecking {name} ({code})")

    url = f"https://api.mfapi.in/mf/{code}"

    response = requests.get(url)

    print("Status Code:", response.status_code)

    try:
        data = response.json()

        df = pd.DataFrame(data["data"])

        df.to_csv(
            rf"C:\Users\madhu\mutual_fund_analytics\data\raw\{name}.csv",
            index=False
        )

        print(f"{name} saved successfully")

    except Exception as e:
        print(f"Error for {name}:")
        print(e)
        print("Response Text:")
        print(response.text[:500])

Checking SBI_Bluechip (119551)
Status Code: 502
Error for SBI_Bluechip:
Expecting value: line 1 column 1 (char 0)
Response Text:
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.24.0</center>
</body>
</html>


Checking ICICI_Bluechip (120503)
Status Code: 502
Error for ICICI_Bluechip:
Expecting value: line 1 column 1 (char 0)
Response Text:
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.24.0</center>
</body>
</html>


Checking Nippon_LargeCap (118632)
Status Code: 502
Error for Nippon_LargeCap:
Expecting value: line 1 column 1 (char 0)
Response Text:
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.24.0</center>
</body>
</html>


Checking Axis_Bluechip (119092)
Status Code: 200
Axis_Bluechip saved successfully

Checking Kotak_Bluechip (120841)
Status Code: 200
Kotak_Bluechip saved successfully

In [21]:
with open(
    r"C:\Users\madhu\mutual_fund_analytics\reports\day1_data_quality.txt",
    "w"
) as f:

    f.write("DAY 1 DATA QUALITY REPORT\n")
    f.write("="*50 + "\n\n")

    f.write(f"Total Funds: {fund_master['amfi_code'].nunique()}\n")
    f.write(f"Total Fund Houses: {fund_master['fund_house'].nunique()}\n")
    f.write(f"Total Categories: {fund_master['category'].nunique()}\n")
    f.write(f"Total Sub Categories: {fund_master['sub_category'].nunique()}\n")
    f.write(f"Total Risk Categories: {fund_master['risk_category'].nunique()}\n\n")

    f.write("AMFI Validation Completed Successfully\n")
    f.write("Missing AMFI Codes: 0\n")

print("Report Created Successfully")

Report Created Successfully

In [23]:
import os
print(os.getcwd())

C:\Users\madhu